name: tbarguig_demo
description: TBARGUIG - demo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^6.1.2

  # UI / fonts / icons
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.6.0

  # state / storage / localization
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  easy_localization: ^3.0.5

  # maps & location
  google_maps_flutter: ^2.7.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1

  # networking & caching
  http: ^1.2.2
  cached_network_image: ^3.4.1

  # firebase (optional â€” for realtime / users positions)
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/